name: CI Tests

on:
  push:
    branches:
      - master
      - feature/CICDTask
  pull_request:
    branches:
      - master
      - feature/CICDTask
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser for UI tests'
        required: true
        default: chrome
        type: choice
        options:
          - chrome
          - edge

jobs:
  api-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet test [ApiTests.csproj](http://_vscodecontentref_/1) --configuration Release --logger "trx;LogFileName=api-tests.trx" --results-directory artifacts/test-results/api
      - if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: artifacts/test-results/api/**/*.trx
          if-no-files-found: warn